goodrain/rainbond-ui

src/components/AppCreateSetting/index.js
src/routes/App/resource.js
src/routes/Group/AddServiceComponent.js

1. fix bug for http://jira.goodrain.org/browse/RAINBOND-550?filter=-1
2. moidfy golang runtimes

[REV] fix bug 550 and modify golang runtimes

---

src/routes/Group/EditorData.js

[REV] Modifying the  Bug 549

---

src/utils/appLogSocket.js

bix bug by 537
url:http://jira.goodrain.org/browse/RAINBOND-537?filter=-4&jql=issuetype%20%3D%20Bug%20AND%20assignee%20in%20(currentUser())%20order%20by%20created%20DESC

[FIX] fix bug by 537 for modifing websocket close

---

src/components/HttpTable/index.js
src/routes/Index/Index.js
src/services/gateWay.js

1. fix bug by RAINBOND-557
2. url: http://jira.goodrain.org/browse/RAINBOND-557?filter=-1
3. after adding HTTP, make sure that the last edit information appears when adding HTTP again
4. formate code

[FIX] fix bug 557

---

src/routes/Group/EditorData.js
src/routes/Group/Index.js

[REV] Modifying the  Bug 562 Topology editing is not available

[REV] Modifying the  Bug 562 Topology editing is not available

---

src/routes/Group/EditorData.js

Topology updating and optimization
修改拓扑图更新，优化。

[REV] Topology updating and optimization

---

src/routes/Group/Index.js

[REV] Modified topological diagram switching display problem

---

src/components/visitBtnForAlllink/index.js
src/routes/App/index.js
src/routes/App/overview.js
src/routes/Index/Index.js

1. modify visitBtn link
2. formate code
3. delete debug log

[REV] modify visitBtn link

---

src/routes/Group/EditorData.js
src/routes/Group/EditorTopology.js
src/routes/Group/Index.js
src/services/app.js

新增拓扑图删除连接线功能
Added topology diagram to delete connector function

[ADD] Delete Topology Map Function

---

package.json
src/components/AddRelationMnt/index.js
src/components/AppCreateSetting/index.js
src/components/AppCreateSetting/setting.less
src/components/HttpTable/index.js
src/components/VisitBtn/index.js
src/components/visitBtnForAlllink/index.js
src/models/appControl.js
src/routes/App/index.js
src/routes/App/mnt.js
src/routes/App/port.js
src/routes/App/relation.js
src/routes/App/resource.js
src/routes/App/resource.less
src/routes/App/setting.js
src/routes/Group/Index.js
src/routes/Index/Index.js
src/routes/Index/Index.less

1. formate code
2. modify style and text
3. fix bug
4. optimize the code

[REV] modify text、style、formate code、delete debug log

---

src/routes/App/index.js
src/routes/Group/AddServiceComponent.js
src/routes/Group/EditorData.js

1. modify depends on the wired port exception
2. modify management of the container text

[REV] modify port 

---

package.json
src/routes/App/log.js

[REV] Log rolling modification修改日志滚动

[REV] Log rolling modification

---

src/routes/Group/EditorData.js

Topological diagram pop-up box 拓扑图弹框修改

[REV] Modify the topological diagram pop-up box

---

src/components/HttpTable/index.js
src/components/VisitBtn/index.js
src/components/visitBtnForAlllink/index.js
src/routes/Group/EditorData.js

modify the way when open a new link

[REV] modify link blank

---

src/routes/App/setting/edit-run-health-check.js

[REV] modify health check

---

package.json
src/routes/Create/code-custom.js
src/routes/Create/code-github.js
src/routes/Create/code-goodrain.js
src/routes/Create/image-cmd.js
src/routes/Create/image-name.js
src/routes/Create/market.js
src/routes/Group/EditorData.js
src/routes/Group/EditorTopology.js
src/routes/Group/Index.js
src/routes/Plugin/Index.less

Topology layout modification

---

src/components/CodeCustomForm/index.js
src/components/CodeGithubForm/index.js
src/components/CodeGoodrainForm/index.js
src/components/ImageCmdForm/index.js
src/components/ImageNameForm/index.js
src/routes/Create/code-goodrain.js
src/routes/Group/AddServiceComponent.js
src/routes/Group/EditorData.js

[REV] Update tips for modifying topology diagrams

---

src/components/GlobalHeader/index.js
src/routes/App/resource.js
src/routes/Group/AddServiceComponent.js
src/utils/utils.js

Change the language link address

[REV] Change the language link address

---

src/routes/Group/EditorData.js

[REV] Topology adds dependencies to refresh the page

---

src/components/ImportBackup/index.js

[REV] fix bug with 592 and formate code

---

src/components/LogProcress/index.js
src/routes/App/Index.less
src/routes/App/overview.js

[REV] Change log scroll and  Modify the bug 617

---

src/routes/Finance/index.js

Recharge must be the administrator of the current team

[REV] Recharge must be the administrator of the current team

---

src/components/AppVersionManage/index.js
src/routes/App/index.js
src/routes/App/overview.js
src/services/app.js
src/utils/app-action-log-util.js

[REV] Modify build version management

---

src/routes/Finance/index.js

Query again after adding the team

[REV] Query again after adding the team

---

src/components/SiderMenu/SiderMenu.js

[REV] modify logo style

---

src/components/Team/TeamMemberList/index.js
src/index.ejs
src/index_old.ejs

[REV] modify loading style

---

src/index.ejs
src/routes/Source/AppExporter.js

[REV] modify user-bg url

---

src/components/WelcomeAndJoinTeam/index.js
src/config/config.js
src/models/global.js
src/routes/App/log.js
src/services/api.js

[REV] Modify the bug 647

---

src/config/config.js
src/routes/App/index.js
src/routes/Finance/index.js
src/routes/Group/AppList.js
src/routes/Group/AppShape.js
src/routes/Group/Index.js

Modify the application upgrade click after the operation

---

src/components/HttpTable/index.js

[FIX] fix bug with RAINBOND-661

---

src/components/AppInstanceList/index.js
src/routes/App/expansion.js

修改bug 660 实例资源使用的显示图不完整，有性能问题

---

src/components/GlobalHeader/index.js
src/models/appControl.js
src/routes/App/resource.js
src/routes/App/setting.js
src/routes/App/setting/auto-deploy.js
src/services/app.js

[REV] Add automatic deployment

---

src/routes/App/Log.less
src/routes/App/expansion.js
src/routes/App/index.js
src/routes/App/log.js
src/routes/App/resource.js

[REV] Modify Style of logging

---

src/config/config.js
src/index.ejs
src/layouts/BasicLayout.js
src/layouts/MemoryTip.js
src/models/global.js
src/routes/App/index.js
src/utils/request.js

[REV] modify global service code

---

src/models/appControl.js
src/routes/App/setting/auto-deploy.js

[REV] Modify Style of Customised build

---

src/components/AppCreateSetting/index.js
src/components/CreateTeam/index.js
src/components/DAinput/index.js
src/components/DrawerForm/index.js
src/components/GlobalHeader/index.js
src/components/buildPluginVersion/index.js
src/models/appControl.js
src/routes/App/Log.less
src/routes/App/expansion.js
src/routes/App/index.js
src/routes/App/overview.js

[REV] Modify the bug 664 666

---

src/routes/App/expansion.js

[REV] Modify the bug 666

---

src/components/buildPluginVersion/index.js

[REV] Modify the Build logs show problems

---

src/components/AddRelationMnt/index.js
src/components/AppVersionManage/index.js
src/routes/App/overview.js
src/utils/date-util.js

[REV] Modify the Build information width

---

src/common/menu.js
src/components/DrawerForm/index.js
src/components/TcpDrawerForm/index.js
src/layouts/BasicLayout.js
src/routes/App/index.js
src/routes/App/relation.js
src/routes/Group/Index.js

[REV] Modify the BUG  700、 697

---

src/components/CodeCustomForm/index.js
src/components/OuterCustomForm/index.js
src/routes/App/index.js
src/routes/Create/create-check.js
src/routes/Group/AppList.js

 Modify the  BUG 762

---

public/images/third_party.svg
src/components/DrawerForm/index.js
src/components/HttpTable/index.js
src/components/OuterCustomForm/index.js
src/components/TcpTable/index.js
src/routes/App/index.js
src/routes/App/resource.js
src/routes/App/setting/edit-buildsource.js
src/routes/Create/create-check.js
src/routes/Create/create-compose-check.js
src/routes/Create/create-compose-setting.js
src/routes/Create/create-setting.js
src/routes/Group/EditorTopology.js

访问策略添加成功后，下一次继续添加策略时数据为清空
[REV] Modify the  BUG 775 771 第三方服务在拓扑图编辑模式下显示错误 第三方服务在编辑模式下的拓扑图有问题
REV] Modify the  BUG 774 修改构建源时，表单无法正确的判断地址是SSH类型还是HTTP类型。导致无法更改用户名密码
REV] Modify the  BUG 780  添加服务组件，取消后服务未删除

[REV] Modify the  BUG 785访问策略添加成功后，下一次继续添加策略时数据为清空

---

src/components/DrawerForm/index.js
src/routes/App/index.js
src/routes/Group/AddServiceComponent.js
src/routes/Group/AddThirdParty.js
src/routes/Group/AppList.js
src/routes/Group/Index.js
src/routes/Index/Index.js

[REV] Modify the  Bug 780 808 首页热么服务无法点击,   添加服务组件，取消后服务未删除

---

src/routes/App/setting.js
src/utils/appProbe-util.js

[REV] Modify the  Bug 844

---

src/components/CodeDemoForm/index.js
src/components/Port/index.js

[REV] Modify the Access strategy show

---

src/components/HttpTable/index.js
src/routes/Create/create-check.js
src/routes/Group/AddServiceComponent.js

构建镜像名称错误，修改后无法触发重新识别
应用网关 - 访问控制，搜索后无法翻页

Modify the Bug 851 860

---

src/models/appControl.js
src/routes/App/setting/auto-deploy.js
src/services/app.js

Automatic build Settings modification

---

src/routes/Guide/index.js
src/routes/Guide/index.less

[REV] The novice guides the front arrow position

---

src/routes/Create/create-check.js
src/routes/Create/create-compose-setting.js
src/routes/Create/create-moreService.js
src/routes/Create/create-setting.js

[ADD] Third party service creation button

---

release.sh
src/components/ImageCmdForm/index.js
src/components/ImageComposeForm/index.js
src/services/createApp.js

[ADD] New private repository functionality under Docker image

---

src/components/HttpTable/index.js
src/components/ParameterForm/index.js

[ADD] Parameter configuration adds new parameters

---

src/components/HttpTable/index.js
src/components/TcpTable/index.js
src/routes/App/setting/auto-deploy.js
src/services/gateWay.js

[REV] Access control, page cannot be turned after searching

---

src/components/AddOrEditVolume/index.js
src/components/DrawerForm/index.js
src/components/EditPortAlias/index.js
src/components/LicenseDrawer/index.js
src/components/ParameterForm/index.js
src/components/SetMemberAppAction/index.js
src/components/TcpDrawerForm/index.js
src/routes/App/port.js
src/routes/App/setting/edit-health-check.js
src/routes/App/setting/env.js
src/routes/App/setting/perm.js
src/routes/Team/edit_action.js

[REV] Edit the popover of the class by clicking on the outer not closing

---

src/routes/Guide/index.js

[REV] Language link cannot click function

---

src/components/HttpTable/index.js

[REV] Parameter configuration popover problem

---

src/routes/Create/create-check.js
src/routes/Create/modify-image-cmd.js

[REV] Create service process front-end exception BUG handling

---

src/routes/Create/create-check.js
src/routes/Create/create-compose-check.js
src/routes/Create/modify-image-cmd.js
src/routes/Create/modify-image-name.js

[REV] Build the source display

---

src/routes/Group/AddThirdParty.js

[REV] Modify the Add third party service page stuck

---

src/components/AppCreateSetting/index.js
src/routes/App/resource.js

[REV] Modify the Node version shows the problem

---

src/components/VisitBtn/index.js

[REV] Modify the Access information display

---

src/components/AppCreateSetting/index.js
src/routes/App/connectionInformation.js
src/routes/Index/Index.js

[REV] Modify the advanced Settings environment variable display

---

src/components/LogProcress/index.js
src/routes/App/overview.js

修改错位日志显示问题， 现在都显示id为box 里面 不会出现显示错位问题!

[REV] Change log display

---

src/routes/App/index.js

[ADD]  service close button second confirmation function

---

src/common/router.js
src/models/global.js
src/routes/Group/Index.js
src/routes/Upgrade/index.js
src/routes/Upgrade/index.less
src/routes/Upgrade/info-util.js
src/routes/Upgrade/info.js
src/services/api.js

[ADD]  New cloud city application upgrade function

---

src/components/HttpTable/index.js

[REV] The change to open Websocket does not take effect

---

src/components/AddOrEditEnv/index.js
src/routes/App/relation.js
src/routes/App/setting/env.js

Add an environment variable name validation method

---

src/services/app.js

Modify the type of the parameter #132

---

src/routes/Group/Index.js
src/routes/Upgrade/index.js
src/routes/Upgrade/info.js

Improve cloud city application upgrade

---

src/components/AddStorage/index.js
src/components/AddStorage/mergeindex.js
src/components/AddStorage/relationMnt.js
src/components/AppCreateSetting/index.js
src/routes/App/connectionInformation.js
src/routes/App/customEnvironmentVariables.js
src/routes/App/environmentConfiguration.js
src/routes/App/index.js
src/routes/App/mnt.js
src/routes/App/relation.js
src/routes/App/setting.js
src/routes/Group/Index.js
src/routes/Upgrade/index.js
src/routes/Upgrade/info.js
src/services/app.js

New environment variable page

---

src/components/OuterCustomForm/index.js

[REV] Add third-party service instance address verification method

---

src/routes/Upgrade/index.js
src/routes/Upgrade/index.less
src/routes/Upgrade/info.js
src/services/api.js

[REV] Improve cloud city application upgrade

---

src/models/groupControl.js
src/routes/Group/AllBackup.js
src/services/group.js

[REV] Add delete failed application backup button under all backup pages

---

src/components/TcpTable/index.js

[REV] Modify gateway access policy control for third party services

---

src/routes/Create/market.js
src/routes/Plugin/Index.less

Modify the style

---

src/routes/App/mnt.js

[REV] Modify type remindInfo

---

src/routes/Upgrade/info.js

[REV] Modify the parameters

---

src/routes/App/mnt.js
src/services/app.js

修改bug、948挂载共享储存”看不到其他服务的共享储存了，无法实现挂载

[REV] Modify the Transfer parameter change

---

src/components/CreateAppFromMarketForm/index.js
src/routes/Create/market.js
src/services/createApp.js
src/services/market.js

[REV] ADD the The cloud application

---

src/models/appControl.js
src/routes/App/connectionInformation.js
src/routes/App/customEnvironmentVariables.js
src/routes/App/relation.js
src/services/app.js

[REV] Modify the Service connection information Paging add function

---

src/components/Port/index.js

[REV] Modify port protocol display problem

---

src/components/AuthCompany/index.js
src/routes/Source/AppList.js

[REV] Modify the Error binding jump address for cloud city

---

src/routes/App/Index.less
src/routes/App/plugin.js
src/routes/Group/AppShare.js

复选框点击问题 解决方式https://github.com/ant-design/ant-design/issues/8880

[REV] Modify the Style

---

src/routes/App/overview.js
src/routes/Create/market.js
src/routes/Plugin/Index.less

Delete the Rollback this version of the display

Delete the Rollback this version of the display

---

src/components/ViewRelationInfo/index.js
src/models/appControl.js
src/routes/App/relation.js

修改 依赖上游应用的连接信息显示不全 ＃171

---

Dockerfile
Dockerfile.base

Add the installation package to the base image for subsequent builds.

[ADD] create image  rainbond/rbd-ui-base:V5.1

---

src/routes/Index/Index.js
src/routes/Index/Index.less
src/utils/global.js

[REV] Fix the the home style

---

src/routes/App/component/Instance/index.js

[REV] Fix the the instanceStyle

---

src/components/CodeCustomForm/index.js

[REV] Fix the the Subdirectory paths are not displayed in SVG

---

src/routes/App/Index.less
src/routes/App/component/Basic/index.js
src/routes/App/component/Basic/operation.less
src/routes/App/component/BuildHistory/index.js
src/routes/App/overview.js
src/routes/App/resource.js

[REV] Fix the the style

---

src/routes/App/component/Basic/operationRecord.js
src/utils/global.js

[REV] Fix the the text show and style

---

src/components/Team/TeamEventList/index.js
src/components/Team/TeamEventList/index.less
src/routes/Index/Index.js

[REV] Fix the the Team dynamic

---

src/routes/App/component/Basic/operationRecord.js
src/routes/App/component/LogShow/index.js
src/routes/App/log.js
src/routes/App/monitor.js
src/routes/App/overview.js

[REV] Fix the socket check

---

src/routes/App/log.js

[REV] Modify the 1000 logs

---

src/routes/App/Log.less
src/routes/App/log.js

[REV] Modify the 1000 logs style

---

src/components/DrawerForm/index.js

[REV] Modify the Add a policy

---

src/components/Port/index.js
src/components/TcpDrawerForm/index.js
src/components/TcpDrawerForm/portInput.js
src/components/TcpTable/index.js
src/services/gateWay.js

[REV] Modify the gateway ip

---

src/components/AppCreateSetting/index.js
src/routes/App/connectionInformation.js
src/routes/App/customEnvironmentVariables.js
src/routes/App/relation.js
src/routes/App/setting.js
src/services/app.js

（修改 删除 转移 ）变量的参数attr_name 换成 ID

[REV] Modify the environment variable ginseng ID

---

src/routes/Group/AddServiceComponent.js
src/utils/rainbond.js

[REV] Modify the gitlab_config validation

---

src/common/menu.js
src/components/AuthCompany/index.js
src/components/Authorized/AuthorizedRoute.js
src/components/CodeDemoForm/index.js
src/components/GlobalHeader/index.js
src/components/Login/index.js
src/components/OuterCustomForm/index.js
src/components/Team/TeamDataCenterList/index.js
src/components/WelcomeAndJoinTeam/index.js
src/layouts/BasicLayout.js
src/layouts/UserLayout.js
src/models/global.js
src/models/user.js
src/routes/App/setting/auto-deploy.js
src/routes/Create/code.js
src/routes/Create/create-check.js
src/routes/Create/create-compose-check.js
src/routes/Create/market.js
src/routes/Group/AddServiceComponent.js
src/routes/Guide/index.js
src/routes/Index/Index.js
src/routes/Source/AppList.js
src/routes/Source/PluginList.js
src/routes/Team/index.js
src/utils/configureGlobal.js
src/utils/request.js
src/utils/utils.js

新增限制
1、新手引导功能
2、文档功能
3、导出应用功能
4、官方Demo功能
5、云应用市场功能
6、数据中心功能

Limit function

---

src/routes/Group/AppShare.js

[REV] Modify the Support image preview

---

src/components/OpenRegion/index.js

Enterprise edition clues no show

---

src/components/CodeCustomForm/index.js
src/components/OuterCustomForm/index.js
src/routes/App/setting/edit-buildsource.js

通过源码创建应用时，仓库地址 更改 校验判断 http: https:  。

[REV] Modify the Validation rules http: https:

---

src/components/AppCreateSetting/index.js
src/components/Dockerinput/index.js
src/routes/App/resource.js

[REV] fix the The ARG parameter could not be saved correctly

---

src/routes/Create/market.js
src/routes/Source/CloudApp.js

[REV] Modify the Network anomalies cloundMarket

---

src/components/TcpTable/index.js
src/routes/App/resource.js
src/routes/Create/create-check.js
src/routes/Create/create-compose-check.js

[REV] Modify the name

---

src/components/Ansi/index.ts

[REV] Modify the log indentation

---

src/components/GlobalHeader/index.js
src/components/Port/index.js
src/components/Team/TeamDataCenterList/index.js
src/routes/App/ThirdPartyServices.js
src/routes/Create/create-check.js

[REV] Modify the create show

---

src/routes/Group/Index.js
src/utils/team.js

[REV] Modify the space

---

src/components/CodeDemoForm/index.js
src/components/GlobalHeader/index.js
src/components/OuterCustomForm/index.js
src/components/Team/TeamDataCenterList/index.js
src/models/global.js
src/routes/App/setting/auto-deploy.js
src/routes/Create/code.js
src/routes/Create/create-compose-check.js
src/routes/Create/market.js
src/routes/Group/AddServiceComponent.js
src/routes/Guide/index.js
src/routes/Index/Index.js
src/routes/Index/Indexs.js
src/routes/Source/AppList.js
src/routes/Source/Index.js
src/routes/Source/PluginList.js
src/utils/rainbond.js

[REV] Modify the Feature set

---

src/components/AuthCompany/index.js
src/components/ChangePassword/index.js
src/components/CodeCustomForm/index.js
src/components/CodeDemoForm/index.js
src/components/ImageCmdForm/index.js
src/components/ImageComposeForm/index.js
src/components/ImageNameForm/index.js
src/components/OuterCustomForm/index.js
src/components/TcpDrawerForm/index.js
src/components/TcpDrawerForm/portInput.js
src/components/TcpTable/index.js
src/components/VisitBtn/index.js
src/routes/App/component/Basic/operationRecord.js
src/routes/App/component/Instance/index.js
src/routes/Create/market.js
src/routes/Index/Index.js
src/routes/Source/CloudApp.js

修改了  
1、语言的描述  
2、路由规则的校验 
3、跳转云应用市场链接 
4、监听所有IP（0.0.0.0）时，访问界面没有给出合适的访问路径

[REV] Modify the style and Description. and fix bug

---

src/components/CodeCustomForm/index.js
src/components/OuterCustomForm/index.js
src/index.ejs
src/routes/App/setting/edit-buildsource.js
src/routes/Create/modify-url.js

[REV] Modify the Check the warehouse address

---

src/components/SiderMenu/SiderMenu.js

[REV] Modify the Select the applied style

---

src/layouts/UserLayout.js
src/layouts/UserLayout.less
src/utils/rainbond.js

merge master into V5.1

---

src/components/CreateAppFromMarketForm/index.js
src/components/VisitBtn/index.js
src/index.ejs
src/routes/App/component/Basic/operation.less
src/routes/App/component/Basic/operationRecord.js
src/routes/App/component/Instance/index.js
src/routes/Create/market.js

[REV] Modify the Local application installation jump

---

src/common/menu.js
src/components/SiderMenu/SiderMenu.js
src/layouts/BasicLayout.js

[REV] Modify the  Selection state

---

src/routes/GateWay/license.js

[REV] Modify the  Certificate management style

---

src/components/Port/index.js

[REV] Modify the Foreign service clues

---

src/routes/App/Index.less
src/routes/App/component/Basic/operationRecord.js

[REV] View logs position and font problem.

---

src/models/global.js

[REV] Modify the Authorization expired

---

package.json
src/routes/App/Index.less
src/routes/App/component/AddScaling/index.js

Modify the styles

---

src/utils/rainbond.js

[REV] Modify the oauth_services value

---

src/components/AppCreateSetting/index.js
src/routes/App/relation.js

[REV] Modify the delete Component description

---

src/components/ThirdList/index.js
src/routes/User/Login.js

[REV] Modify the oauth detection

---

src/routes/App/Index.less
src/routes/App/expansion.js

[REV] Modify the scale detection

---

src/components/OauthForm/index.js

[REV] Modify the parameter

---

src/models/user.js
src/routes/User/Third.js
src/routes/User/ThirdLogin.js
src/routes/User/ThirdRegister.js
src/services/user.js
src/utils/oauth.js

[REV] Modify the oauth Authentication failed compatibility

---

src/components/OauthForm/index.js
src/components/OpenRegion/index.js
src/components/ThirdList/form.js
src/components/ThirdList/index.js
src/models/groupControl.js
src/models/user.js
src/routes/Create/code.js
src/routes/Finance/index.js
src/routes/Group/AppShare.js
src/routes/Group/AppShareRecord.js
src/routes/Group/Index.less
src/routes/User/Third.js
src/routes/User/ThirdLogin.js
src/routes/User/ThirdRegister.js
src/services/app.js
src/services/group.js
src/services/user.js
src/utils/oauth.js

Publishingmarket

---

src/routes/Group/AppShare.js
src/services/group.js

[REV] Modify the  code

---

src/common/enterpriseMenu.js
src/components/GlobalRouter/index.js
src/components/SiderMenu/SiderMenu.js
src/layouts/EnterpriseLayout.js
src/pages/Create/market.js
src/services/createApp.js
src/utils/user.js

fix the Normal user navigation

---

src/components/GlobalRouter/index.js
src/components/SiderMenu/SiderMenu.js
src/pages/Create/market.js
src/services/createApp.js

[REV] Install local market applications

---

src/components/GlobalRouter/index.js
src/components/SiderMenu/SiderMenu.js
src/pages/Create/market.js
src/pages/Enterprise/index.js
src/services/createApp.js

fix the 企业视图、团队页面、后台统计中资源使用报告不一致

fix the Inconsistent resource usage reports in enterprise view, team page, and background statistics

---

src/components/AddAdmin/index.js
src/pages/EnterpriseSetting/index.js

fix the There was a problem adding an enterprise administrator interface jump

---

src/components/SiderMenu/SiderMenu.js
src/layouts/EnterpriseLayout.js

[REV] fix the The navigation bar does not see the team

---

src/components/AddAdmin/index.js
src/components/Convenient/index.js
src/pages/EnterpriseUsers/index.js
src/services/api.js

[REV] fix the The user manages the page creation time

---

src/components/EditableLinkGroup/index.js
src/pages/EnterpriseSetting/index.js

[REV] fix the 'whether to allow users to register

---

src/pages/EnterpriseSetting/index.js

[REV] Modify the Allow users to register

---

src/models/groupControl.js
src/pages/Group/Backup.js
src/services/group.js
src/utils/logSocket.js

[Add]  new Forced to backup function

---

src/pages/EnterpriseSetting/index.js
src/pages/User/Login.js
src/utils/rainbond.js

[REV] Modify the Oauth third party authentication failed

---

src/models/user.js
src/pages/User/Register.js
src/pages/User/registerComponent.js

[ADD] Registration page

---

src/components/CreateAppModels/index.js
src/pages/Group/AppShare.js
src/pages/Group/AppShareLoading.js
src/services/market.js

[REV] Modify the Sharing process code

---

src/components/SiderMenu/SiderMenu.js
src/layouts/EnterpriseLayout.js
src/layouts/TeamLayout.js

[REV] Modify the enterpriseID

---

src/components/CodeCustomForm/index.js
src/components/CodeDemoForm/index.js
src/components/CodeGithubForm/index.js
src/components/CodeGoodrainForm/index.js
src/components/CreateAppFromMarketForm/index.js
src/components/ImageCmdForm/index.js
src/components/ImageNameForm/index.js
src/components/OuterCustomForm/index.js
src/components/ThirdList/form.js
src/models/global.js
src/pages/Create/code-custom.js
src/pages/Create/image-cmd.js
src/pages/Create/image-compose.js
src/pages/Create/image-name.js
src/pages/Create/outer-custom.js
src/pages/Guide/index.js
src/pages/TeamDashboard/Index.js

[REV] Modify the The new application is not selected

---

src/utils/global.js

[REV] Modify the Component type description

---

src/components/RestoreBackup/index.js
src/pages/EnterpriseSetting/index.js
src/pages/Group/Index.js

[REV] Modify the Backup management restore function

---

src/layouts/TeamLayout.js
src/pages/Create/market.js
src/pages/EnterpriseCloudMarket/index.js
src/pages/Source/AppList.js

fix The Shared library installation application did not respond to clicking install

---

src/components/Lists/index.js
src/layouts/EnterpriseLayout.js
src/layouts/TeamLayout.js
src/pages/EnterpriseSetting/index.js
src/pages/EnterpriseTeams/index.js
src/pages/User/ThirdLogin.js
src/pages/User/ThirdRegister.js

修复 oauth绑定后提示‘认证成功’跳转问题
修复 源码创建选择oauth代码仓库，页面显示问题
修复 oauth绑定后提示‘认证成功’跳转问题

[REV] Modify the Oauth binding prompts' authentication successful 'jump

---

src/pages/EnterpriseSetting/index.js
src/pages/Group/AppShare.js
src/pages/Group/Index.js
src/pages/Group/Publish.js
src/pages/Plugin/share-steptwo.js
src/services/group.js

Modify the share function

---

src/components/PageHeader/index.less
src/pages/Enterprise/index.js

[REV] Modify the styles

---

src/components/Convenient/index.js

[REV] Modify the Convenient entrance function

---

src/routes/App/resource.js

[REV] Modify the The build source does not show the recognized language

---

src/components/AppStore/index.js
src/components/AuthCompany/index.js
src/components/Consulting/index.js
src/components/JoinTeam/index.js
src/components/WelcomeAndJoinTeam/index.js
src/layouts/SecurityLayout.js
src/models/user.js
src/pages/Enterprise/index.js
src/pages/EnterpriseTeams/index.js
src/utils/global.js
src/utils/request.js

[REV] Modify the Obtain business solutions

---

src/components/SelectStore/index.js
src/components/ShowRegionKey/index.js
src/pages/EnterpriseCloudMarket/CloudApp.js
src/pages/Group/AppShare.js
src/services/group.js
src/services/market.js

[REV] Modify the The app is published to the cloud app store

---

src/components/AddDomain/index.js
src/components/DrawerForm/index.js
src/routes/App/port.js
src/services/team.js

[REV] Modify the Certificate support paging

---

src/pages/Component/resource.js
src/pages/Group/AppShare.js
src/utils/app.js

修改 创建方式： 本地共享库 或者云应用商店 两种。
云市应用名称 更改为  应用模版名称

[REV] Modify the text

---

src/components/AuthCompany/index.js
src/pages/Enterprise/index.js

[REV] Modify the Bind store permissions

---

src/services/team.js

[REV] Modify the Port opening failed

---

src/components/CodeBuildConfig/golang/index.js
src/components/CodeBuildConfig/java-jdk/index.js
src/components/CodeBuildConfig/netcore/index.js
src/components/CodeBuildConfig/nodejs/index.js
src/components/CodeBuildConfig/php/index.js
src/components/CodeBuildConfig/python/index.js
src/components/CodeBuildConfig/static/index.js

[REV] Modify the The build source close cache button shows a problem

---

src/pages/AppList/index.js

[REV] Modify the The new application

---

src/components/Lists/index.js
src/pages/EnterpriseSetting/index.js
src/pages/EnterpriseShared/index.js
src/pages/EnterpriseUsers/index.js

修复： 共享库没有权限 点击按钮会出现不让点击的样式 
修复： 加强的企业权限的页面

[REV] Modify the styles and permissions

---

src/pages/EnterpriseShared/index.js
src/pages/Group/AppShare.js
src/pages/Group/Index.js

修复 编辑应用模版完成后，应用模版的选择项
修复 版本号校验
修复 发布按钮持续处于loading 状态
修复删除应用后应该跳转

[REV] Modify the Application sharing process show

---

src/components/CreateAppModels/index.js
src/pages/Group/AppShare.js
src/services/market.js

[REV] Modify the Creating application templates

---

src/pages/EnterpriseCloudMarket/index.js

[REV] Modify the The ability to interconnect across clusters

---

src/pages/Group/ComponentList.js

[REV] Modify the Apply the list view page-turning jump exception

---

src/components/VisitBtn/index.js
src/layouts/SecurityLayout.js
src/pages/Component/index.js
src/pages/Component/overview.js

[REV] Modify the Deleting a component does not require an interface

---

src/components/VisitBtn/index.js
src/pages/Component/index.js
src/pages/Component/overview.js

[REV] Modify the Optimize timer control

---

src/components/SelectComponent/index.js

[REV] Modify the See applying all component jumps

---

src/components/CreatUserForm/index.js
src/components/TenantSelect/index.js
src/pages/EnterpriseUsers/index.js
src/services/api.js

[REV] Modify the Add user function

---

src/pages/TeamDashboard/Index.js
src/utils/global.js

[REV] Modify the Novice boot configuration

---

mock/chart.js
src/components/LogProcress/index.js
src/components/StandardTable/index.js
src/components/Team/TeamDataCenterList/index.js
src/pages/Component/component/BuildHistory/index.js
src/pages/Component/component/Instance/index.js
src/pages/Component/expansion.js
src/pages/EnterpriseUsers/index.js
src/pages/Group/ComponentList.js
src/pages/Group/Publish.js
src/pages/List/Articles.js
src/pages/List/BasicList.js
src/pages/Team/index.js
src/pages/TeamDashboard/Index.js
src/pages/TeamDashboard/Indexs.js
src/utils/global.js
src/utils/monitorDataUtil.js

[REV] Modify the Time zone problem

---

src/components/GlobalHeader/index.js

[REV] Modify the oauth_services show

---

src/pages/User/registerComponent.js
src/utils/rainbond.js

[REV] Modify the firstRegist

---

src/layouts/TeamLayout.js
src/layouts/components/AppHeader.js
src/layouts/components/TeamHeader.js
src/models/global.js
src/pages/Component/index.js
src/pages/Group/Index.js
src/pages/Team/index.js

修复 ：组件视图修改组件名称跳转到空白页面
修复 ：应用 团队 组件 修改名称后导航刷新

[REV] Modify the The component view modifies the component name

---

src/components/HttpTable/index.js
src/pages/Component/setting/auto-deploy.js
src/utils/date-util.js

修复 ： 自动构建的文档地址跳转问题
修复 ： 提示框无法关闭转问题
修复 ： 应用分享时，提示 消息通道不可用 关闭问题

[REV] Modify the The prompt box closes the jump prompt message display

---

src/models/global.js
src/pages/EnterpriseUsers/index.js
src/services/api.js

[REV] Modify the create user the clues

---

src/components/Convenient/index.js
src/models/global.js
src/pages/Enterprise/index.js
src/services/api.js
src/services/user.js

修改 ： 集群的数据  便捷入口 前端控制分页后端返回所有数据

[REV] Modify the New shortcut entry data changes

---

src/pages/Component/component/AddScaling/index.js

[REV] Modify the Horizontal auto scaling, availability of parameters

---

src/pages/Group/AppShare.js

[REV] Modify the Release parameters

---

src/pages/Component/component/Basic/operationRecord.js

[REV] Modify the The operation record reflects the specific time

---

src/components/SiderMenu/SiderMenu.js
src/components/SiderMenu/index.less

[REV] Modify the height

---

src/components/ChangePassword/index.js
src/components/GlobalHeader/index.js

[REV] Modify the Support users to change their own passwords

---

src/components/AppCreateSetting/index.js
src/components/ViewRelationInfo/index.js
src/pages/Component/Index.less
src/pages/Component/connectionInformation.js
src/pages/Component/customEnvironmentVariables.js
src/pages/Component/relation.js
src/utils/global.js

修复:  变量名里有 （PASS、pass）就 隐藏。
修复:  不需要在所有变量之后都有眼睛图标，只需要在加密的值后面展示。

[REV] Modify the Hide the display of environment variables

---

src/components/CreatePluginForm/index.js
src/services/plugin.js

[REV] Modify the Plug-in fill in the warehouse account password

---

src/components/CreatePluginForm/index.js

[REV] Modify the Plug-in pass-through problem

---

src/components/Convenient/index.js
src/components/RapidCopy/index.js
src/components/RapidCopy/index.less
src/models/groupControl.js
src/pages/Group/Index.js
src/services/group.js
src/utils/app.js

ADD  Rapid replication function

---

config/router.config.js
src/layouts/ErrorBoundary.js
src/layouts/SecurityLayout.js
src/models/global.js
src/pages/Enterprise/index.js
src/services/api.js

ADD Exception handling

---

src/utils/global.js

[REV] Modify the log

---

package.json
src/models/global.js
src/pages/Component/WebConsole/index.js
src/pages/Component/WebConsole/index.less
src/pages/Component/WebConsole/xTerm/index.js

[REV] Modify the xterm

---

src/layouts/ErrorBoundary.js

[REV] Modify the saveLog parameter

---

src/layouts/TeamLayout.js
src/pages/EnterpriseTeams/index.js
src/services/api.js

[REV] Modify the Docking cluster

---

src/pages/Component/WebConsole/index.js
src/pages/Component/WebConsole/xTerm/index.js

[REV] Modify the web terminal

---

package.json
src/components/AddStorage/index.js

[REV] Modify the Restore configuration file

---

src/components/CodeBuildConfig/index.js
src/components/CodeBuildConfig/java-jdk/index.js

修复 Java源码构建 选择 自定义JDK 功能  传递环境变量：
BUILD_ENABLE_ORACLEJDK = true

[REV] Modify the Java source code builds the custom JDK

---

src/layouts/SecurityLayout.js

[REV] Modify the Unsend putLog

---

src/pages/Component/WebConsole/index.less
src/pages/Component/WebConsole/xTerm/index.js

[REV] Modify the Web terminal style

---

config/router.config.js
src/components/AccesstokenForm/index.js
src/components/GlobalHeader/index.js
src/components/GlobalHeader/index.less
src/layouts/AccountLayout.js
src/layouts/EnterpriseLayout.js
src/layouts/TeamLayout.js
src/locales/zh-CN.js
src/locales/zh-CN/settings.js
src/models/global.js
src/pages/Account/Center/AccesstokenView.js
src/pages/Account/Center/BindingView.js
src/pages/Account/Center/Info.js
src/pages/Account/Center/Info.less
src/services/api.js
src/utils/oauth.js

[ADD] Personal center

---

src/components/AppCreateSetting/index.js
src/pages/Create/create-check.js

[REV] Modify the Advanced Settings

---

src/components/GitRepostory/index.js

[REV] Modify the The docked Oauth2 all disappeared

---

src/components/VisitBtn/index.js
src/models/appControl.js
src/models/global.js
src/models/index.js
src/pages/Component/index.js
src/pages/Component/overview.js
src/pages/Group/Index.js
src/pages/TeamDashboard/Index.js
src/pages/TeamDashboard/Indexs.js
src/services/api.js
src/services/app.js
src/services/team.js
src/utils/team.js

[REV] Modify the Front-end polling optimization

---

src/pages/EnterpriseTeams/index.js

[REV] Modify the  The admin team page is not paginated

---

src/pages/Plugin/index.js
src/utils/plugin.js

[REV] Modify the The new plug-in

---

src/pages/EnterpriseCloudMarket/CloudApp.js
src/pages/EnterpriseCloudMarket/index.js

[REV] Modify the Cloud application synchronization page paging function

---

src/pages/Create/market.js
src/pages/Plugin/Index.less

[REV] Modify the Shared library application version list style

---

src/components/VisitBtn/index.js
src/pages/Component/index.js
src/pages/Component/overview.js
src/utils/appStatus-util.js

[REV] Modify the team delete

---

src/pages/Plugin/index.js
src/utils/plugin.js

[REV] Modify the plug

---

src/components/Topological/index.js
src/services/api.js

[REV] Modify the region_name

---

src/pages/Component/index.js

[REV] Modify the Rollback

---

src/layouts/TeamPermissions.js
src/models/teamControl.js
src/pages/EnterpriseTeams/index.js
src/services/team.js

新增 企业 团队 管理 下 点击集群 请求加入团队接口 然后跳转

[REV] Modify the join team

---

src/pages/Group/AppShare.js

修复 多实例组件分享，节点步长设置为1，最小/最大节点是按节点步长递增的

Modify the Increasing node step size

---

src/components/AddOrEditVolume/index.js
src/components/AddRelationMnt/index.js
src/components/AddStorage/mergeindex.js
src/layouts/UserLayout.js
src/pages/Enterprise/index.js
src/pages/List/BasicList.less
src/pages/User/registerComponent.js
src/utils/plugin.js

修复 1、企业名称显示
2、存储配额问题
3、存储挂载问题
4、企业视图首页显示的内存使用量不显示单位，CPU却显示单位

Modify the  Storage mount  and  Storage quota and style

---

src/components/VisitBtn/index.js
src/pages/Component/index.js
src/pages/Component/overview.js
src/pages/Group/Index.js

Modify the  Remove components

---

src/layouts/UserLayout.js

Modify the  oauth Jump

---

src/components/RapidCopy/index.js

Modify the  appCopy

---

src/models/appControl.js
src/pages/Component/index.js
src/services/app.js

Components delete

---

src/components/CodeDemoForm/index.less
src/components/GitRepostory/index.js
src/pages/Component/resource.js

Modify the  oauth According to certification

---

src/components/BatchDelete/index.js
src/pages/Component/component/BuildHistory/index.js
src/pages/Component/component/Instance/index.js
src/pages/Component/monitor.js
src/pages/EnterpriseUsers/index.js
src/pages/Group/Publish.js
src/pages/List/Articles.js
src/pages/List/BasicList.js
src/pages/TeamDashboard/Index.js
src/utils/monitorDataUtil.js

修复 
1、时间24小时制
2、按钮文字的修改
3、文字的修改

Modify the  24 system time and  Name of monitoring and Button text

---

src/pages/Component/index.js

Modify the  state interface polling

---

src/pages/EnterpriseTeams/index.js
src/pages/Team/index.js
src/services/team.js

Modify the  delete team

---

src/components/GitRepostory/index.js
src/components/ThirdList/Index.less
src/components/ThirdList/form.js
src/pages/Component/resource.js
src/pages/Component/resource.less
src/services/createApp.js

oauth gitlab Component building problem

---

src/components/SiderMenu/CollectionView.js

修改：新建收藏后再次新建时，输入框中带有上一次添加收藏的信息，输入框为空

Modify the  Optimization of collection function

---

src/layouts/SecurityLayout.js
src/layouts/UserLayout.js

Modify the  emptyCookie

---

src/components/AddOrEditEnv/index.js
src/components/EnvironmentVariable/index.js
src/models/appControl.js
src/pages/Component/setting/env.js
src/services/app.js

Modify the  Variable check input Chinese error

---

package.json

Modify the  engines

---

src/components/CodeCustomForm/index.js
src/components/CreatePluginForm/index.js
src/components/ShowRegionKey/index.js

Modify the Configure authorization check

---

src/pages/EnterpriseShared/AppExporter.js
src/pages/EnterpriseShared/ExportOperation.js
src/pages/EnterpriseShared/index.js

修复  1、应用市场管理下 本地组件库 应展示最新版本
2、导出应用地址

Modify the  Shared application display should show the latest version

---

src/components/TcpTable/index.js

Modify the  clues

---

src/pages/Create/market.js
src/services/createApp.js

Modify the  App Store installation

---

src/components/CreateAppModels/index.js
src/pages/Enterprise/index.js
src/pages/EnterpriseImport/index.js
src/pages/TeamDashboard/Index.js

Modify the  Application of the template url

---

src/pages/EnterpriseShared/TagList.js
src/pages/EnterpriseShared/index.js

Modify the  tags

---

src/components/RapidCopy/index.js
src/services/group.js
src/utils/request.js

Modify the  fast copy

---

release.sh

通过遍历 BUILD_RBD_APP_UI 去决定是否构建 rbd-app-ui 镜像

var BUILD_RBD_APP_UI

---

src/components/CreateTeam/index.js
src/components/JoinTeam/index.js
src/pages/Component/setting/auto-deploy.js
src/utils/global.js

创建团队时新增loading 
webhook文档链接调整 
修改文字 组件部署类型

Modify the  team loading

---

src/pages/Group/AppShare.js

Modify the  Publish Shared library error

---

.webpackrc.dev.js
src/pages/User/Login.js
src/pages/document.ejs

Modify the  TAB icon

---

src/pages/User/Login.js
src/pages/User/loginComponent.js

Modify the  Request certification

---

src/pages/User/Login.js
src/pages/User/loginComponent.js

Modify the  oauthList login

---

src/pages/User/Login.js

Modify the  console

---

src/pages/Group/AppShare.js

Modify the  Issue application transfer reference problem

---

src/pages/Group/AppShare.js

修复  应用发布环境变量
修复  发布应用时点击取消某个组件触发前端故障，无法取消

Modify the Release application

---

src/components/Cluster/EditClusterInfo/index.js

Modify the regular

---

package.json
src/models/createApp.js
src/pages/Create/create-setting.js
src/services/createApp.js

Modify the Create components to increase loading

---

src/pages/Component/component/Basic/operationRecord.js
src/pages/Component/component/BuildHistory/index.js
src/pages/Component/component/LogShow/index.js
src/pages/Component/component/LogShow/index.less
src/utils/downLoadTools.js

Add the download Log

---

src/components/SiderMenu/index.less
src/locales/zh-CN/sidecar.js

Modify the Console left bar optimization improvements

---

src/components/AppMoveGroup/index.js
src/components/BatchDelete/index.js
src/components/ConfirmModal/index.js
src/components/EnvironmentVariable/index.js
src/models/appControl.js
src/pages/Component/connectionInformation.js
src/pages/Component/customEnvironmentVariables.js
src/pages/Component/index.js
src/pages/Group/ComponentList.js
src/pages/Group/Index.js
src/services/app.js

修复 ：应用和组件的以下功能按钮需要二次确认：构建、更新、停止、启动 、修改名称、删除、新增、批量操作。 
环境变量的增删改查第二次确认

Modify the loading state

---

src/components/ImageHubForm/index.js

Modify the parameter

---

src/pages/Component/index.js
src/pages/Group/ComponentList.js

Modify the Secondary confirmation loading

---

src/pages/Upgrade/info.js

修改了 应用市场 （升级按钮、回滚按钮） 加了 加载过渡动画 loading

Modify the Application market upgrade loading

---

src/pages/Component/component/Basic/index.js
src/pages/Component/component/BuildHistory/index.js
src/pages/Component/overview.js

Add the Build history paging

---

src/layouts/UserLayout.js
src/layouts/UserLayout.less
src/pages/User/Login.js
src/pages/User/Third.js
src/utils/request.js

Solution: jump back to the address again clear token

Fix bug : New cloud users need to log in twice

---

src/pages/Component/index.js

Fix bug : Text description

---

src/components/HttpTable/index.js
src/components/ParameterForm/index.js

Fix bug : Parameter to configure buffer number buffer size

---

src/components/CustomChart/index.js
src/components/CustomChart/rangeChart.js
src/pages/Component/monitor.js

一、fix the component resource flow status is not displayed
二、solution : K8s_POD_ ${serviceId} for stateless and k8s_POD_${serviceAlias} for stateful
三、test results component resource flow status display

Fix bug : Component resource flow status is not displayed

---

src/models/global.js
src/pages/EnterpriseSetting/infrastructure.js
src/services/api.js

To solve the problem ：object storage operation
solution ： Check the code
The test results  ： Object storage operates normally

Fix bug : Add, delete, change check of object storage

---

src/pages/Group/ComponentList.js
src/pages/Group/Index.js

Modify the batch operation and Form the paging

---

src/components/Convenient/index.js
src/components/SiderMenu/SiderMenu.js
src/services/user.js

1、To solve the problem ： The collection function is in normal use
2、solution ： Code review
3、test results ： The collection function is in normal use

Fix bug : Collection function

---

src/models/monitor.js
src/pages/Component/component/monitor/customMonitor.js
src/services/monitor.js

New feature :  Business monitoring Key Import

---

src/components/AddCustomMonitor/index.js

1、To solve the problem ：The monitoring configuration collection interval cannot be entered as 0 or -1
2、solution ：Input add check
3、test results  : The monitoring configuration collection interval cannot be entered as 0 or -1

Fix bug : The monitoring configuration collection interval cannot be entered as 0 or -1

---

src/pages/Group/Index.js

1、To solve the problem ：Apply overview button state control
2、solution ：By applying state judgment
3、test results : The Application Overview button is displayed in its normal state

Fix bug : Apply overview button state control

---

src/pages/EnterpriseShared/index.js

1、To solve the problem ： Application market button, simply click ➕ number add
2、solution ：Click the event to move to the parent level
3、test results ：Optimized the click mode of application market buttons

Fix bug : Application market button, simply click ➕ number add

---

src/components/ApplicationGovernance/index.js
src/pages/Component/port.js
src/pages/Group/Index.less

1、To solve the problem ：Domain name format check
2、solution ：Modify the regular
3、test results : Domain name format validation must consist of lowercase letters, Numbers, and - _, and must begin with letters, end with Numbers, and letters

Fix bug :  Domain name format check

---

src/components/GlobalRouter/index.js
src/components/SiderMenu/CollectionView.js
src/components/SiderMenu/SiderMenu.js
src/layouts/EnterpriseLayout.js
src/layouts/TeamLayout.js
src/models/user.js

New feature :  Left menu new favorites

---

src/pages/Guide/index.js
src/pages/TeamDashboard/Index.js

New feature :   Apply view new search box

---

src/components/Team/TeamMemberList/index.js
src/services/team.js

1、To solve the problem ：Handover team fails
2、solution ：Changed the pass parameter value
3、test results : Successful handover of team

Fix bug Handover team fails

---

src/components/AuthCompany/index.js
src/components/CreatePluginForm/index.js
src/pages/Create/Index.less
src/utils/plugin.js

1、To solve the problem ：Select one of the application store bindings
2、solution ：Select the app Store to pass the value
3、test results : Select one of the application store bindings

Fix bug Select one of the application store bindings

---

src/styles/codemirror.less

1、To solve the problem ：CodeMirror amplification function
2、solution ：Style 
3、test results : CodeMirror Zoom function and Version

Fix bug CodeMirror amplification function

---

src/pages/Plugin/index.js

1、To solve the problem ：Uninstalled plug-ins enter details to report an error
2、solution ：Added a judgment has_install
3、test results : Uninstalled plug-ins cannot access details

Fix bug Uninstalled plug-ins enter details to report an error

---

src/components/ApplicationGovernance/index.js

1、To solve the problem ：Applying governance mode toggle mode to change missing prompt
2、solution ：The new tips
3、test results : Apply governance mode toggle mode to change the new prompt

Fix bug Applying governance mode toggle mode to change missing prompt

---

src/components/BatchDelete/index.js

1、To solve the problem ： Inconsistent feedback when removing components
2、solution ：translation
3、test results : Consistent feedback when deleting components

Fix bug  Inconsistent feedback when removing components

---

src/components/EnvironmentVariable/index.js

1、To solve the problem ： Cannot save after adding environment variables
2、solution ：Add container_port after adding the environment variable
3、test results : Environment variables can be saved after they are added

Fix bug  Cannot save after adding environment variables

---

package.json
src/components/LicenseDrawer/index.js
src/pages/Create/create-compose-check.js

1、To solve the problem ： react-codemirror Zoom function
2、solution ： delete codemirror
3、test results : react-codemirror Zoom function

Fix bug  react-codemirror Zoom function

---

src/models/plugin.js
src/pages/Plugin/index.js
src/services/plugin.js

1、To solve the problem ： Plug-ins in use are removed without prompting
2、solution ：The new tips
3、test results : A new prompt when a plug-in in use is removed

Fix bug Plug-ins in use are removed without prompting

---

src/components/CustomChart/index.js
src/models/monitor.js
src/pages/Component/component/monitor/customMonitor.js
src/services/monitor.js

1、To solve the problem ： Business monitoring ordering is out of order
2、solution ：handleSorting
3、test results : Business monitoring sort

Fix bug Business monitoring ordering is out of order

---

src/components/AuthCompany/index.js
src/models/market.js
src/services/market.js

1、To solve the problem ： Docking wrong cloud application store, did not give a hint
2、solution ：alertText
3、test results : Give a hint to the wrong cloud app store

Fix bug Docking wrong cloud application store, did not give a hint

---

src/components/AuthCompany/index.js
src/models/market.js
src/services/market.js
src/utils/request.js

1、To solve the problem ： Determine if the URL of the bound application market is normal
2、solution ：Interface return processing
3、test results : Determine if the URL of the bound application market is normal

Fix bug Determine if the URL of the bound application market is normal

---

src/pages/EnterpriseShared/Details.js
src/services/market.js

1、To solve the problem ：Add pagination to the application template version list
2、solution ：page page_size total
3、test results : Add pagination to the application template version list

Fix bug Add pagination to the application template version list

---

src/components/AddOrEditConfig/index.js

1、To solve the problem ：Plug-in configuration group modification failed
2、solution ：onChange
3、test results : The plug-in configuration group has been modified successfully

Fix bug Plug-in configuration group modification failed

---

src/pages/Create/create-moreService.js

Reverts goodrain/rainbond-ui#618

Revert "Fix bug  When the source code builds a Maven multi-module project, th…"

---

src/components/CustomChart/rangeChart.js

Modify the Resource monitoring style

---

src/pages/Create/create-moreService.js

1、To solve the problem ： The Maven multi-module project failed to build
2、solution ：serviceIds
3、test results : The Maven multi-module project has been successfully built

Fix bug The Maven multi-module project failed to build

---

src/components/CodeBuildConfig/php/index.js

1、To solve the problem ： PHP Demo source code build failed
2、solution ：PHP version
3、test results : PHP demo source code built successfully

Fix bug PHP Demo source code build failed

---

src/pages/Component/component/Basic/operationRecord.js
src/pages/Component/component/LogShow/index.js
src/pages/Component/component/LogShow/index.less
src/utils/downLoadTools.js

1、To solve the problem ： The log window cannot be opened while in build state
2、solution ：bodyText
3、test results : The log window can be opened in the build state

Fix bug The log window cannot be opened while in build state

---

src/pages/Component/resource.js

1、To solve the problem ： Build source editing
2、solution ：loading
3、test results : Build source editing

Fix bug Build source editing

---

src/components/ParameterForm/index.js
src/components/ParameterForm/index.less
src/components/Parameterinput/index.js

Modify the The gateway parameter configuration page presents the problem

---

src/pages/Create/create-moreService.js

1、To solve the problem ：Source build Maven multi-module build failed
2、solution ：regionName
3、test results : Source build Maven multi-module build successfully

Fix bug Source build Maven multi-module build failed

---

src/pages/Component/resource.js

1、To solve the problem ：The modified build source is optional for Oauth Server
2、solution ：OAuth Server
3、test results : The modified build source is optional for Oauth Server

Fix bug The modified build source is optional for Oauth Server

---

src/components/CustomChart/index.js
src/components/CustomChart/index.less
src/components/CustomChart/rangeChart.js
src/components/HttpTable/index.js
src/pages/Component/component/monitor/customMonitor.js

1、To solve the problem ：The monitor diagram shows a query for the time
2、solution ：Monitor graph multi-data processing and converData
3、test results : Monitoring graph multi-data display can be time query

Fix bug The monitor diagram shows a query for the time

---

src/components/Parameterinput/index.js

1、To solve the problem ：The gateway parameter configuration page presents the problem
2、solution ：Row Col
3、test results : The gateway parameter configuration page is perfect

Fix bug The gateway parameter configuration page presents the problem

---

src/pages/EnterpriseUsers/index.js
src/pages/User/registerComponent.js
src/utils/cloud.js

1、To solve the problem ：User prompt creation is incorrect
2、solution ：handleCloudAPIError
3、test results : Create the correct user prompt

Fix bug User prompt creation is incorrect

---

src/components/Lists/index.js

Modify the Application market... Style

---

src/components/CodeMirrorForm/index.js
src/components/CodeMirrorForm/index.less
src/styles/codemirror.less

1、To solve the problem ：Configuration file editing, full screen feature not available
2、solution ：fullScreens
3、test results : Configuration file editing, full screen feature available

Fix bug Configuration file editing, full screen feature not available

---

src/utils/cloud.js
src/utils/rainbond.js

new function cluster install

---

src/pages/Group/AppShare.js

一、To solve the problem ：publishing component model configuration
二、solution ：form
三、test results :Modify the publishing component model configuration

Fix the publishing component model configuration

---

src/pages/Group/AppShare.js

1、To solve the problem ：Environment variables are not required at publication time
2、solution ：required false
3、test results : Environment variables are not required at publication time

Fix the Environment variables are not required

---

src/components/AddCustomMonitor/index.js
src/components/AddOrEditVolume/index.js
src/components/AddStorage/index.js
src/components/AppDirector/index.js
src/components/EnvironmentVariable/index.js
src/pages/Component/Index.less
src/pages/Component/setting/edit-buildsource.js
src/pages/Group/Index.js
src/services/team.js

1、To solve the problem ：length limit and View Styles
2、solution ：rules
3、test results : Modify the  length limits and the width style

Fix the style and check

---

src/components/AddOrEditConfig/index.js
src/components/CreatePluginForm/index.js
src/components/RestoreBackup/index.js
src/pages/Component/component/Basic/operation.less
src/pages/Component/component/Basic/operationRecord.js
src/pages/Component/resource.js
src/pages/EnterpriseSetting/oauthTable.js

1、To solve the problem ：text and  Length limit and View Log Styles
2、solution ：rules
3、test results : Modify the successful text and length limits and the normal view log style

Fix the style and check and text

---

src/pages/Group/AppShare.js

1、To solve the problem ：Publish environment variable pass-value changes
2、solution ：newinfo
3、test results : The release environment variable was successfully modified

Fix bug the Publish environment variable pass-value changes

---

src/pages/Component/plugin.js
src/pages/Group/AppShare.js

1、To solve the problem ：There is a delay in the input field of the application publishing page when there are too many components in the application
2、solution ：TabPane
3、test results : Will there be a delay in the input field of the app release page when there are too many components in the app

Fix  the Application release data multi-optimization operation function

---

src/components/CodeBuildConfig/golang/index.js
src/components/CodeBuildConfig/index.js
src/components/CodeBuildConfig/java-maven/index.js
src/components/CreatUserForm/index.js
src/pages/EnterpriseUsers/index.js
src/pages/Group/Backup.js
src/utils/cloud.js

、To solve the problem ：default Golang version and Text modification and length check and translation error codes
2、solution ：text and rules and case 2003
3、test results : Successful text modification and length check and translation error code and default Golang version

Fix bug the default Golang version and Optimize the code

---

config/config.js
src/components/Team/TeamRoleList/permissionsForm.js
src/pages/Component/setting.js
src/pages/Component/setting/edit-health-check.js
src/pages/EnterpriseSetting/management.js
src/pages/Team/move_team.js

1、To solve the problem ：The code style is not elegant
2、solution ：Optimization of code style

Fix the Code Optimization

---

src/components/HttpTable/index.js
src/components/Search/index.js
src/components/TcpTable/index.js

1、To solve the problem ：Error in text style
2、solution ：Text style optimization

Fix the Error in text style

---

src/pages/Group/Backup.js
src/pages/Group/ComponentList.js

1、To solve the problem ：The style of the page is flawed
3、test results : Defect repair is completed

Fix the Stylistic optimization of code

---

src/components/AddStorage/index.js
src/components/CodeMirrorForm/index.js
src/components/CodeMirrorForm/index.less

1、To solve the problem ： codemirror style
2、solution ：width
3、test results :  codemirror style

Fix bug the codemirror style

---

config/config.js
src/pages/Group/Index.js

1、To solve the problem ：Insufficiently optimized to be upgraded

Fix the optimizations to upgrade

---

src/components/DrawerForm/index.js

1、To solve the problem ：Lack of code optimization

Fix the Lack of code optimization

---

src/pages/Group/ComponentList.js

1、To solve the problem ：Code optimization is lacking
2、solution ： Code Optimization

Fix the Code optimization is lacking

---

src/pages/Group/Publish.js
src/pages/Group/publish.less

1、To solve the problem ：Tips for releasing an application version
2、solution ：Added prompt function

Add the version of the tip

---

config/config.js
src/components/CreatUserForm/index.js
src/pages/EnterpriseUsers/index.js

1、To solve the problem ：Add the email and phone parts

Add the email and phone parts

---

src/pages/Group/Backup.js

1、To solve the problem ：Fix the loading of backup

Fix the loading of backup 

---

src/layouts/EnterpriseLayout.js
src/models/global.js
src/services/api.js

1、To solve the problem ：Enterprise list interface fetch returns null processing
2、solution ：handleJumpLogin
3、test results : If the enterprise list interface fetch returns empty, it will jump to the login page

Fix bug the Gets no return from the enterprise list interface

---

src/components/RapidCopy/index.js
src/pages/Create/create-check.js

1、To solve the problem ： Gets the application replication list parameter to return error handling
2、solution ：buildSource
3、test results :  Gets application replication list parameter compatibility handling

Fix bug the Gets the application replication list parameter to return error handling

---

src/pages/AddCluster/index.js

1、To solve the problem ：The browser Secret Key is populated by default
2、solution ：autoComplete="new-password"
3、test results : Secret Key is not auto-populated

Fix bug the  browser Secret Key is populated by default

---

config/config.js
src/components/DrawerForm/index.js

1、To solve the problem ：Fix the weight of number
2、solution ：Add a check rule for the weight item
3、test results :The defect modification is completed

Fix the weight of number

---

src/components/ThirdList/Index.less
src/components/ThirdList/form.js

New fuction the  OAuth can fill in subdirectories when creating components

---

src/components/AddOrEditConfig/index.js
src/components/ConfirmModal/index.js
src/components/DAinput/index.js
src/components/DrawerForm/index.js
src/components/TcpDrawerForm/index.js

1、To solve the problem ： Location request header Cookie length limit
2、solution ： length limit
3、test results : Location lentgh 65530 header Cookie lentgh 255

Fix bug the  Location request header Cookie length limit

---

src/components/CodeBuildConfig/java-maven/index.js
src/components/ConfirmModal/index.js
src/components/CreateTeam/index.less
src/components/MavenConfiguration/index.js

1、To solve the problem ：  Newly created teams, components, and Maven configurations are displayed empty
2、solution ：Default_BUILD_MAVEN_SETTING_NAME
3、test results : The newly created team, component, and Maven configuration display is not empty

Fix bug the Newly created teams, components, and Maven configurations are displayed empty

---

src/components/HttpTable/index.js
src/components/ParameterForm/index.js

1、To solve the problem ：Header key cannot be deleted
2、solution ：set_headers
3、test results : The header key can be empty

Fix bug the  Header key cannot be deleted

---

src/pages/Group/ComponentList.js

1、To solve the problem ：The list of components shows 10 by default
2、solution ：delete ScrollerX
3、test results : The list of components shows 10 by default

Fix bug the  The list of components shows 10 by default

---

src/components/AppInstanceList/index.js

1、To solve the problem ：Instance clicks cannot jump
2、solution ：delete a 
3、test results : Instances cannot be clicked and cannot jump

Fix bug the  Instance clicks cannot jump

---

src/components/ComponentVersion/index.js
src/components/CreateTeam/index.less
src/models/appControl.js
src/models/application.js
src/pages/Upgrade/index.js
src/services/app.js
src/services/application.js

New fuction the Batch upgrade components

---

src/pages/Component/members.js
src/pages/Component/setting/edit-health-check.js

1、To solve the problem ：Third party component health check status is not in effect
2、solution ：fetchBaseInfo
3、test results : Third party component health check status is in effect

Fix bug the Third party component health check status is not in effect

---

src/components/AddOrEditGroup/index.js
src/components/LicenseDrawer/index.js
src/pages/Component/port.js
src/pages/Group/Index.js

1、To solve the problem ：Certificate Name Verification length 64
2、solution ：max: 64
3、test results : Certificate Name Verification length 64

Fix bug the  Certificate Name Verification length 64

---

src/components/DrawerForm/index.js
src/components/HttpTable/index.js
src/components/HttpTable/index.less

1、To solve the problem ：Advanced Routing Demonstration
2、solution ：CopyToClipboard
3、test results : Advanced Routing Demonstration

Fix bug the  Advanced routing

---

src/components/AddOrEditConfig/index.js
src/components/OauthForm/index.js
src/pages/Create/create-check.js
src/pages/Create/create-compose-check.js
src/pages/Create/create-moreService.js
src/pages/Create/create-setting.js

1、To solve the problem ：Abandoning component creation confirms lack of loading and Discard the create button permission and style
2、solution ：currentTeamPermissionsInfo isDelete
3、test results : Abandoning component creation confirms  loading and Discard the create button permission and style

Fix the bug the Abandoning component creation confirms lack of loading and Discard the create button permission and style

---

src/pages/Component/setting/auto-deploy.js

1、To solve the problem ：Automatically builds address defaults
2、solution ：http://127.0.0.1:5000
3、test results : Automatically builds address defaults

Fix bug the Automatically builds address defaults

---

src/components/DrawerForm/index.js
src/components/HttpTable/index.js
src/components/HttpTable/index.less
src/services/gateWay.js

1、To solve the problem ：Click to confirm no response
2、solution ：CopyToClipboard
3、test results : Click OK to modify normally

Fix bug the  Click to confirm no response

---

src/components/TcpDrawerForm/index.js

1、To solve the problem ：TCP Port Limits
2、solution ：internalTcps
3、test results : TCP ports restrict internal ports

Fix bug the  TCP Port Limits

---

src/components/HttpTable/index.js
src/components/TcpTable/index.js

Fix bug the  The deletion policy is confirmed twice

---

src/pages/Component/setting/edit-health-check.js

1、To solve the problem ：The number of times a health test passes can only be 1
2、solution ：isRestart
3、test results : The unhealthy treatment method is to restart the health test pass times can only be 1

Fix bug the  The number of times a health test passes can only be 1

---

src/components/DrawerForm/index.js

1、To solve the problem ：Gateway access policy is not displayed correctly
2、solution ：loading
3、test results : Gateway access policy display adds loading

Fix bug the  Gateway access policy is not displayed correctly

---

src/components/Cluster/CustomClusterAdd/index.js
src/components/Cluster/KubernetesTableShow/index.js
src/components/Cluster/RKEClusterAdd/index.js
src/components/Cluster/RKEClusterUpdate/index.js
src/utils/utils.less

1、To solve the problem ：Host installs Kubernetes cluster to add node data processing
2、solution ：this.clusters 
3、test results : Host installs Kubernetes cluster to add nodes normally

Fix  the  Host installs Kubernetes cluster to add node data processing

---

src/components/Convenient/index.js
src/components/CurrentTeams/index.js
src/components/RapidCopy/index.js
src/components/SelectTeam/index.js
src/components/SiderMenu/SiderMenu.js
src/models/global.js
src/pages/EnterpriseImport/index.js
src/pages/EnterpriseTeams/index.js
src/services/api.js

Fix the  fetchMyTeams api

---

src/components/AddOrEditConfig/index.js
src/components/OauthForm/Index.less
src/components/ThirdList/form.js
src/pages/EnterpriseTeams/index.js

1、To solve the problem ：Prompt font overlap
2、solution ：style
3、test results :The prompt font does not overlap

Fix bug the Prompt font overlap

---

src/components/CodeCustomForm/index.js
src/components/ImageCmdForm/index.js
src/components/ImageComposeForm/index.js
src/components/ImageNameForm/index.js
src/components/OuterCustomForm/index.js
src/components/ThirdList/form.js

1、To solve the problem ：Create a component based on an image, no next step
2、solution ：showSubmitBtn
3、test results :To create a component based on an image, there is the next step

Fix bug the Create a component based on an image, no next step

---

src/components/AddMember/index.js
src/components/CurrentTeams/index.js
src/models/user.js
src/services/user.js

1、To solve the problem ：Failed to set role
2、solution ：this. handleError
3、test results :Set Character Successfully

Fix bug the Failed to set role

---

src/components/CreatUserForm/index.js
src/pages/EnterpriseUsers/index.js

1、To solve the problem ：Modifying user mailboxes is not supported
2、solution ：! userInfo
3、test results :"Modifying user mailboxes is not supported

Fix bug the Modifying user mailboxes is not supported

---

src/components/CodeBuildConfig/java-maven/index.js
src/components/MavenConfiguration/index.js

1、To solve the problem ： Remove the default Maven prompt
2、solution ：isDefaultMaven
3、test results : Remove the default Maven prompt

Fix bug the Remove the default Maven prompt

---

src/components/AppInstanceList/index.js
src/components/AppInstanceList/index.less
src/pages/Group/Backup.js
src/utils/global.js

1、To solve the problem ： It can be exported if the cloud backup fails and list of strengths is centered
2、solution ：isExport
3、test results : Cannot export after cloud backup failure and list of strengths is centered

Fix bug the It can be exported if the cloud backup fails and list of strengths is centered

---

src/components/RapidCopy/index.js

1、To solve the problem ：The copy error application list displays an error
2、solution ：noSaveGroups
3、test results : The list of applications that failed to copy is displayed properly

Fix bug the The copy error application list displays an error

---

src/pages/Account/Center/BindingView.js
src/pages/User/Third.js
src/utils/request.js

1、To solve the problem ：OAuth authentication failure is not indicated
2、solution ：msg_show
3、test results :"OAuth authentication failure prompts the user

Fix bug the OAuth authentication failure is not indicated

---

src/pages/Account/Center/AccesstokenView.js

1、To solve the problem ： Prompt for modification
2、solution ：平台API
3、test results : Suggest that the modification was successful

Fix bug the  Prompt for modification

---

src/components/ImageComposeForm/index.js
src/models/appControl.js
src/pages/Create/create-check.js
src/services/app.js

1、To solve the problem ： Component does not exist after abandoned creation
2、solution ：handleJump
3、test results : After abandoning the creation of the component does not exist directly jump to the team overview page

Fix bug the Component does not exist after abandoned creation

---

src/components/AccesstokenForm/index.js
src/components/AddOrEditConfig/index.js
src/components/AuthCompany/index.js
src/components/ChangePassword/index.js
src/components/CloudBackupForm/index.js
src/components/CodeCustomForm/index.js
src/components/CodeDemoForm/index.js
src/components/CodeGithubForm/index.js
src/components/CodeGoodrainForm/index.js
src/components/ImageCmdForm/index.js
src/components/ImageHubForm/index.js
src/components/ImageNameForm/index.js
src/components/OuterCustomForm/index.js
src/components/PlatformBasicInformationForm/index.js
src/pages/User/registerComponent.js

1、To solve the problem ： New form length check
2、solution ：The rules property of the form performs the form length check
3、test results :form length check

Fix the  Form checks

---

src/components/CreateAppModels/index.js
src/components/SelectStore/index.js
src/pages/Group/AppShare.js
src/pages/Group/Publish.js
src/services/market.js
src/utils/request.js

1、To solve the problem ： Release store version control creates application templates to display selected industries
2、solution ：The release record STORE_VERSION = 2.0 shows the industry name
3、test results :Release store version 2.0 control creates application templates to display selected industries

Fix bug the  Release store version control creates application templates to display selected industries

---

src/components/AddOrEditGroup/index.js
src/components/CodeCustomForm/index.js
src/components/CodeDemoForm/index.js
src/components/CodeGithubForm/index.js
src/components/CodeGoodrainForm/index.js
src/components/CreateAppFromMarketForm/index.js
src/components/ImageCmdForm/index.js
src/components/ImageNameForm/index.js
src/components/OuterCustomForm/index.js
src/components/RapidCopy/index.js
src/components/SelectApp/index.js
src/components/ThirdList/form.js
src/models/global.js
src/pages/AppList/index.js
src/pages/Group/Index.js
src/pages/Guide/index.js
src/pages/TeamDashboard/Index.js
src/services/team.js

1、To solve the problem ： New application is not standard prompt after the confirmation button has been turned, cannot proceed to the next step
2、solution ：IsAddGroup defines whether or not to add an application. IsGetGroups defines a list of requested applications
3、test results :Loading for new application

Fix bug the  New application is not standard prompt after the confirmation button has been turned, cannot proceed to the next step

---

src/components/AddOrEditGroup/index.js
src/components/RapidCopy/index.js
src/pages/Component/customEnvironmentVariables.js
src/pages/EnterpriseSetting/backup.js
src/services/application.js
src/services/backup.js
src/services/team.js
src/utils/request.js

1、To solve the problem ： Api Error handling mechanism
2、solution ：Call the API directly using Nomodels to go through the Models layer and call the API using HandleError
3、test results : Api Error handling mechanism  handleError and noModels

Fix bug the  Api Error handling mechanism

---

src/pages/Upgrade/UpgradeInfo/info.js
src/pages/Upgrade/index.js

Fix   the  Upgrade log new details

---

src/components/CreateAppFromMarketForm/index.js
src/pages/Create/market.js

1、To solve the problem ：Added  the Install the app button

Add the loading of  addApp container

---

src/pages/Component/component/LogShow/index.js
src/pages/Group/AppShareLoading.js
src/pages/Group/Index.less
src/pages/Group/components/BatchEditPublishComponent/index.js
src/services/application.js

Fix   the  release style

---

src/components/Cluster/BaseAddCluster/index.js
src/components/Cluster/RainbondClusterInit/index.js
src/components/Cluster/ShowInitRainbondDetail/index.js
src/components/Cluster/ShowKubernetesCreateDetail/index.js
src/pages/AddCluster/KClusterList/index.js
src/pages/AddCluster/RainbondInit/index.js
src/utils/global.js

disable_install_cluster_log  Control installation data statistics

New function the Installation data statistics

---

src/pages/Group/Group.js

1、To solve the problem ：If there is an upgradable version, be upgraded to 0
2、solution ：Adjust the API
3、test results :When there is an upgradable version, the upgrade should be displayed normally

Fix bug  the  If there is an upgradable version, be upgraded to 0

---

src/components/Cluster/RainbondClusterInit/index.js

1、To solve the problem ： Initialize the popbox
2、solution ：Return to the data structure has changed
3、test results :One into the page initialization does not pop box

Fix bug  the  Initialize the popbox

---

src/pages/Group/AppShareLoading.js

Status is not successful and has event_id to display the log

Fix   the  logs show

---

src/utils/cookie.js
src/utils/global.js

Fix the removeCookie methods

---

src/layouts/UserLayout.js
src/pages/User/Login.js
src/pages/User/Third.js

1、To solve the problem ：OAuth authentication failure does not jump
2、solution ：The status value changes
3、test results :OAuth authentication failure normal jump

Fix the OAuth authentication failure does not jump

---

config/config.js
src/components/GlobalHeader/index.js
src/utils/global.js
src/utils/rainbond.js
web.conf

1、To solve the problem ： Control logout display and control routing
2、solution ：RainbondUtil. LogoutEnable display and control logged on isHash control routing
3、test results :RainbondUtil. LogoutEnable display and control logged on isHash control routing

Fix   the Control logout display and control routing

---

src/components/CreateHelmAppModels/index.js
src/pages/Group/AddServiceComponent.js

Fix the  application name is displayed

---

src/components/AddOrEditVolume/index.js

Fix the memory name check

---

src/components/Cluster/KubernetesTableShow/index.js

Fix the Reinstall reminder

---

src/components/Cluster/SetRegionConfig/index.js

Fix the API communication prompts

---

src/components/Cluster/ClusterProgressQuery/index.js
src/utils/cloud.js

Fix the Error message display

---

src/components/AppCreateSetting/index.js
src/components/CreatePluginForm/index.js
src/pages/Component/Index.less
src/pages/Component/expansion.js
src/pages/Component/plugin.js
src/pages/Group/AppShare.js
src/services/app.js

new function cpu setting

---

src/pages/Component/index.js

修复问题：第三方组件显示'启动', '更新' 和 '关闭'操作
修复方式：取消了第三方类型的控制 按钮

Fix the Third Party button

---

src/pages/Component/ThirdPartyServices.js
src/pages/Component/members.js
src/pages/Component/setting.js
src/pages/Component/setting/edit-health-check.js
src/pages/Component/setting/health-check.js
src/services/app.js

优化了
1、取消上线按钮
2、健康检测取消'忽略'选项
3、所有实例都支持删除
4、健康检测, 实例,修改, 都需要提醒更新.

Fix the Third Party optimize

---

src/components/Cluster/ClusterComponents/index.js
src/components/Cluster/ClusterComponents/index.less
src/components/Cluster/ClusterProgressQuery/index.js
src/components/Cluster/KubernetesTableShow/index.js
src/components/Cluster/RainbondClusterInit/index.js
src/components/NewbieGuiding/index.js
src/components/NewbieGuiding/index.less
src/services/cloud.js
src/utils/cloud.js

新增功能 Rainbond集群组件 。Provider类型为rke||custom   显示查看组件.
Provider类型为rke或custom安装步骤 InitRainbondRegionOperator 显示查看组件.

Function the Cluster components

---

src/components/ApplicationGovernance/index.js

修复问题：空应用无组件时，不能切换
修复方式：应用无组件不显示表格、直接提示切换成功

Fix the None Example Change the network governance mode

---

src/components/AddStorage/index.js
src/pages/Component/customEnvironmentVariables.js
src/services/app.js

The value of the added permission box is limited from 0 to 777

Fix the configuration file mounting supports permission management

---

src/pages/Component/Log.less
src/pages/Component/log.js
src/services/app.js

Added container filtering logs

new function Logs support container filtering

---

src/components/AppCreateSetting/index.js
src/components/CreatePluginForm/index.js
src/models/appControl.js
src/pages/Component/Index.less
src/pages/Component/component/Basic/index.js
src/pages/Component/component/Instance/index.js
src/pages/Component/expansion.js
src/pages/Component/overview.js
src/pages/Component/plugin.js
src/pages/Group/AppShare.js
src/services/app.js

优化了：CPU单位改成 m, 给出提示 1000m=1core  。
组件页面 - 插件 ，插件的 更新 改为 资源配置。

Fix the CPU related optimization

---

src/components/Cluster/ClusterComponents/index.js
src/components/Cluster/ClusterComponents/index.less
src/components/Cluster/ClusterProgressQuery/index.js
src/utils/cloud.js
src/utils/error.js

修复问题：安装中可以 正常的查看组件
修复方式：steps数据中type中有InitRainbondRegionOperator 就正常显示

Fix the Optimized Rainbond cluster components

---

src/components/AddStorage/index.js
src/components/AppInstanceList/index.js
src/components/Cluster/ClusterComponents/index.js
src/components/Cluster/RKEClusterAdd/index.js
src/components/CreatePluginForm/index.js
src/components/MemoryForm/index.js
src/pages/Component/ThirdPartyServices.js
src/pages/Component/plugin.js

优化了 
1、权限数值校验 ： 权限的数值限制在0-777之间的8进制数
2、新增第三方组件的状态  notready: '未就绪'
3、正确的显示安装命令
4、内存组件统一

Fix the Verify the value of permission

---

src/pages/Component/log.js

1、To solve the problem ：Fix the log

Fix the log

---

src/components/Cluster/RKEClusterAdd/index.js

Fix the Style syntax

---

src/components/AuthCompany/index.js

1、To solve the problem ：Fix the send message to rainstore

Fix the send message to rainstore

---

src/components/CodeBuildConfig/golang/index.js

Fix the  Example source build start command

---

.github/workflows/release-ci-build.yml
src/components/CodeBuildConfig/golang/index.js

1、To solve the problem ：Fix the files

Fix the files

---

src/pages/TeamDashboard/Index.js

1、To solve the problem ：Fix the teamViewPage Fnc

Fix the teamViewPage Fnc

---

src/common/enterpriseMenu.js
src/components/MonitoringForm/index.js
src/pages/GrafanaDashboard/index.js

1、To solve the problem ：Fix the monitoring

Fix the monitoring

---

src/pages/TeamDashboard/Index.js

1、To solve the problem ：Complate the teamViewPage

Complate the teamViewPage

---

src/pages/TeamDashboard/Index.js

1、To solve the problem ：Fix some defects

Fix some defects

---

src/pages/TeamDashboard/Index.js
src/pages/TeamDashboard/Index.less

1、To solve the problem ：Fix the hover status of teamView

Fix the hover status of teamView

---

src/pages/Component/setting/auto-deploy.js

Signed-off-by: Qi Zhang <smallqi1@163.com>

fix: docs link err

---

src/pages/AddCluster/ImportMessage/index.js
src/pages/AddCluster/ImportMessageYaml/index.js
src/pages/ChangeResourceTest/index.js
src/pages/ChangeResourceTest/index.less
src/pages/Component/kubernets.js
src/pages/Resource/index.js

* fix: apply k8s resource interface debugging
* fix: apply the k8s resource interface
* fix: to modify the environment
* fix: naming notations
* fix: under the application of the k8s resources
* fix: resolve bug
* fix: yaml file upload interface linkage
* fix: yaml uploads bug fixes
* fix: deleting test data
Co-authored-by: 徐中林 <10495708+xu-zhonglin@user.noreply.gitee.com>
Co-authored-by: guox <guox@MacBook-Pro-For-Guox.local>

fix: failed to create component from yaml file

---

src/components/OuterCustomForm/index.js
src/pages/Create/create-compose-check.js
src/utils/utils.js

I found that some of the links to the documentation are invalid. This PR update them with the correct URLs.

fix: update docs url

---

src/components/EnvironmentVariable/index.js
src/locales/en-US/component.js
src/locales/zh-CN/component.js

**PR 描述：**  
**环境变量管理优化：新增批量编辑功能**  
添加环境变量批量编辑文本框，支持通过文本格式批量导入/导出环境变量，简化配置流程。  
原有的逐个点击复制粘贴方式操作繁琐，尤其在配置多个环境变量时效率低下。新增批量编辑功能可减少重复操作，提升用户配置效率与体验。  
- 新增文本输入区域，支持以 Dotenv 格式批量输入环境变量。  
- 保留原有单变量编辑功能，兼容两种操作模式。  
https://github.com/user-attachments/assets/bfa7f58c-de74-417f-b936-f57e28433208
Fixes #2242

feat: Add batch editing functionality for environment variables
